In [3]:
import visual_behavior.data_access.loading as loading
import numpy as np
from visual_behavior.ophys.response_analysis.response_analysis import ResponseAnalysis

oeid = 1009495882
dataset = loading.get_ophys_dataset(oeid, include_invalid_rois=False)
session = ResponseAnalysis(
    dataset, 
    overwrite_analysis_files=False, 
    use_extended_stimulus_presentations=True, 
    dataframe_format = 'wide'
)

extracting cached data from 1009495882_499478_200221_VISal_0_cre_line_unknown_MESO.1_behavior_265

/home/dougo/Code/AllenSDK/allensdk/brain_observatory/sync_dataset.py:109: UserWarning: The loaded sync file contains the following deprecated line label keys: {'cam1_exposure', 'cam2_exposure'}. Consider updating the sync file line labels.
  self._check_line_labels()
/home/dougo/Code/AllenSDK/allensdk/brain_observatory/sync_dataset.py:109: UserWarning: The loaded sync file contains the following deprecated line label keys: {'cam1_exposure', 'cam2_exposure'}. Consider updating the sync file line labels.
  self._check_line_labels()
WARNING:root:Could not find valid lines for the following data sources
WARNING:root:acquiring (valid line label(s) = ['2p_acquiring']
ERROR:visual_behavior.ophys.sync.process_sync:Sync photodiode error needs to be fixed. Using assumed monitor delay: 0.0351

resampling mesoscope 2P frame times

TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

In [5]:
dataset.dff_traces

,cell_roi_id,dff
cell_specimen_id,,
NaN,1009545088,"[0.38840303932002346, 0.5979359322674376, 0.72..."
NaN,1009545090,"[0.4042915597911269, 0.3354262242771118, 0.341..."
NaN,1009545092,"[0.8395809866486675, 1.2310508781605964, 0.964..."
NaN,1009545095,"[0.3351044566587599, 0.44210459195678997, 0.35..."
NaN,1009545097,"[0.5122500489690438, 0.6422156251131828, 0.276..."
NaN,1009545100,"[0.6148166101876478, 0.6208755551611758, 0.646..."
NaN,1009545101,"[0.49125865344544906, 1.1082259323307988, 1.25..."

In [6]:
experiment_table = loading.get_filtered_ophys_experiment_table()

In [8]:
experiment_table.loc[oeid]

ophys_session_id                                                1009188505
behavior_session_id                                             1009248812
container_id                                                    1018027813
project_code                             VisualBehaviorMultiscope4areasx2d
container_workflow_state                                         completed
experiment_workflow_state                                           passed
session_name                                      20200221_499478_3imagesG
session_type                                              OPHYS_3_images_G
equipment_name                                                      MESO.1
date_of_acquisition                             2020-02-21 08:31:40.292808
isi_experiment_id                                                994736136
specimen_id                                                      990779724
sex                                                                      F
age_in_days                                                            137
full_genotype                Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt
reporter_line                               ['Ai148(TIT2L-GC6f-ICL-tTA2)']
driver_line                                               ['Vip-IRES-Cre']
imaging_depth                                                          265
targeted_structure                                                   VISal
published_at                                                           NaN
super_container_id                                               990779724
cre_line                                                      Vip-IRES-Cre
session_tags                                                           NaN
failure_tags                                                           NaN
exposure_number                                                          0
model_outputs_available                                              False
location                                                     Vip_VISal_265
has_events                                                            True
session_number                                                           3
Name: 1009495882, dtype: object

In [9]:
from visual_behavior_glm import GLM_analysis_tools as gat

In [4]:
from allensdk.brain_observatory.behavior.behavior_ophys_session import BehaviorOphysSession
session = BehaviorOphysSession.from_lims(oeid)

/home/dougo/Code/AllenSDK/allensdk/brain_observatory/sync_dataset.py:109: UserWarning: The loaded sync file contains the following deprecated line label keys: {'cam1_exposure', 'cam2_exposure'}. Consider updating the sync file line labels.
  self._check_line_labels()
/home/dougo/Code/AllenSDK/allensdk/brain_observatory/sync_dataset.py:109: UserWarning: The loaded sync file contains the following deprecated line label keys: {'cam1_exposure', 'cam2_exposure'}. Consider updating the sync file line labels.
  self._check_line_labels()
WARNING:root:Could not find valid lines for the following data sources
WARNING:root:acquiring (valid line label(s) = ['2p_acquiring']

{'rig_name': 'MESO.1',
 'sex': 'F',
 'age': 'P154',
 'excitation_lambda': 910.0,
 'emission_lambda': 520.0,
 'indicator': 'GCAMP6f',
 'field_of_view_width': 512,
 'field_of_view_height': 512,
 'ophys_experiment_id': 1009495882,
 'experiment_container_id': 1018027813,
 'ophys_frame_rate': 43.0,
 'stimulus_frame_rate': 60.0,
 'targeted_structure': 'VISal',
 'imaging_depth': 265,
 'session_type': 'OPHYS_3_images_G',
 'experiment_datetime': Timestamp('2020-02-21 08:31:40.292808+0000', tz='UTC'),
 'reporter_line': ['Ai148(TIT2L-GC6f-ICL-tTA2)'],
 'driver_line': ['Vip-IRES-Cre'],
 'LabTracks_ID': 499478,
 'full_genotype': 'Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt',
 'behavior_session_uuid': UUID('40118c9d-a56b-4687-b34c-7722497ba247')}

In [5]:
session.cell_specimen_table

,cell_roi_id,height,image_mask,mask_image_plane,max_correction_down,max_correction_left,max_correction_right,max_correction_up,valid_roi,width,x,y
cell_specimen_id,,,,,,,,,,,,
NaN,1009545087,20,"[[False, False, False, False, False, False, Tr...",0,17.5137,6.56764,18.7142,4.17358,False,12,13,142
NaN,1009545088,14,"[[False, False, False, False, False, False, Fa...",0,17.5137,6.56764,18.7142,4.17358,True,21,260,67
NaN,1009545090,16,"[[False, False, False, False, False, False, Fa...",0,17.5137,6.56764,18.7142,4.17358,True,16,424,25
NaN,1009545091,18,"[[False, False, False, False, False, False, Tr...",0,17.5137,6.56764,18.7142,4.17358,False,12,187,182
NaN,1009545092,21,"[[False, False, False, False, False, False, Fa...",0,17.5137,6.56764,18.7142,4.17358,True,17,133,181
NaN,1009545094,16,"[[False, False, False, False, True, True, Fals...",0,17.5137,6.56764,18.7142,4.17358,False,12,244,176
NaN,1009545095,17,"[[False, False, False, False, False, False, Fa...",0,17.5137,6.56764,18.7142,4.17358,True,26,323,161
NaN,1009545097,15,"[[False, False, False, False, False, False, Fa...",0,17.5137,6.56764,18.7142,4.17358,True,18,145,323
NaN,1009545098,14,"[[False, False, False, True, True, True, False...",0,17.5137,6.56764,18.7142,4.17358,False,13,119,245
NaN,1009545099,11,"[[False, False, False, False, True, False, Fal...",0,17.5137,6.56764,18.7142,4.17358,False,15,494,499
NaN,1009545100,14,"[[False, False, False, False, False, False, Tr...",0,17.5137,6.56764,18.7142,4.17358,True,18,202,422
NaN,1009545101,17,"[[False, False, False, False, False, False, Fa...",0,17.5137,6.56764,18.7142,4.17358,True,13,192,374