Doug Ollerenshaw  
2/28/2020

MPE has been continuing to track issue 678 on their system relating to erroneously logged omitted stimuli on frame 0.  
Link here:  
https://apps.powerapps.com/play/0c390d76-4b0c-4f9f-bfbb-d8730c607b8f?tenantId=32669cd6-737f-4b39-8bdd-d6951120d3fc?InstrumentFilter=Beh&IssueID=678&hidenavbar=true  

This issue is better described on github here:  
https://github.com/AllenInstitute/AllenSDK/issues/958  

Chris Mochizuki create two test sessions to attempt to replicate this issue. They are stored in \\allen\programs\braintv\workgroups\nc-ophys\1022\012930  

The notebook below opens those two test sessions and confirms that the error is not present in those test sessions  

HOWEVER, there is a warning being thrown about the lack of an omitted flash log, which was an issue that had been solved in camstim ~ 1 year ago. The version of camstim that created these files was '0.3.37'. Is that the current version?

In [1]:
from visual_behavior import database as db
from visual_behavior.translator.foraging2 import data_to_change_detection_core

import os
import pandas as pd

n

In [2]:
directory = r'\\allen\programs\braintv\workgroups\nc-ophys\1022\012930'.replace('\\','/')

### open files with VBA
(it's not clear why the warning about no omitted flash log is present. Is this the current version of camstim?)

In [7]:
pkl_files = [fn for fn in os.listdir(directory) if fn.endswith('pkl')]
core_data = {}
for fn in pkl_files:
    core_data[fn] = data_to_change_detection_core(pd.read_pickle(os.path.join(directory,fn)))

/home/dougo/Code/visual_behavior_analysis/visual_behavior/translator/foraging2/extract_stimuli.py:106: UserWarning:
there was no omitted_flash_frame_log, but long delays were present that were assumed to be omitted flashes
  warnings.warn('\nthere was no omitted_flash_frame_log, but long delays were present that were assumed to be omitted flashes')
/home/dougo/Code/visual_behavior_analysis/visual_behavior/translator/foraging2/extract_stimuli.py:106: UserWarning:
there was no omitted_flash_frame_log, but long delays were present that were assumed to be omitted flashes
  warnings.warn('\nthere was no omitted_flash_frame_log, but long delays were present that were assumed to be omitted flashes')

In [15]:
core_data[pkl_files[0]]['metadata']['platform_info']['camstim']

'0.3.37'

## in both files, there is no omitted flash on frame 0, so the issue noted by Alex Piet in https://github.com/AllenInstitute/AllenSDK/issues/958 does not exist in these files

In [9]:
core_data[pkl_files[0]]['omitted_stimuli']

     frame        time
0      276    4.599937
1      231    3.849937
2      186    3.099937
3      141    2.349937
4       96    1.599937
..     ...         ...
688  35878  597.965306
689  35833  597.215306
690  35788  596.465306
691  35743  595.715306
692  35698  594.965306

[693 rows x 2 columns]

In [10]:
core_data[pkl_files[1]]['omitted_stimuli']

     frame        time
0       50    0.833346
1      501    8.349985
2      681   11.350053
3      636   10.600053
4      817   13.616736
..     ...         ...
329  35790  596.515371
330  36017  600.298723
331  35972  599.548723
332  36106  601.782036
333  36286  604.782046

[334 rows x 2 columns]

In [16]:
pkl_files

['flash_prob-1.0.pkl', 'flash_prob-0.5.pkl']

In [17]:
core_data[pkl_files[0]]['omitted_stimuli']

     frame        time
0      276    4.599937
1      231    3.849937
2      186    3.099937
3      141    2.349937
4       96    1.599937
..     ...         ...
688  35878  597.965306
689  35833  597.215306
690  35788  596.465306
691  35743  595.715306
692  35698  594.965306

[693 rows x 2 columns]

In [18]:
core_data[pkl_files[0]]['visual_stimuli']

,orientation,image_name,image_category,frame,end_frame,time,duration
0,NaN,im065,im065,5,20,0.083292,0.249973
1,NaN,im065,im065,321,336,5.349937,0.249974
2,NaN,im063,im063,366,381,6.099935,0.249998
3,NaN,im063,im063,1041,1056,17.350007,0.249989
4,NaN,im063,im063,1086,1101,18.099993,0.249996
5,NaN,im063,im063,1629,1644,27.150012,0.249978
6,NaN,im061,im061,1674,1689,27.900010,0.250013
7,NaN,im061,im061,2396,2411,39.933315,0.249999
8,NaN,im077,im077,2441,2456,40.683313,0.249974
9,NaN,im077,im077,3164,3179,52.733140,0.249993
10,NaN,im065,im065,3209,3224,53.483113,0.249999
11,NaN,im065,im065,3796,3811,63.266532,0.250000
12,NaN,im077,im077,3841,3857,64.016568,0.266642
13,NaN,im077,im077,4383,4399,73.049914,0.266667
14,NaN,im063,im063,4429,4444,73.816544,0.250022
15,NaN,im063,im063,5016,5031,83.599858,0.249999
16,NaN,im062,im062,5061,5076,84.349855,0.249977
17,NaN,im062,im062,5781,5796,96.349848,0.249870
18,NaN,im077,im077,5826,5841,97.099717,0.249999
19,NaN,im077,im077,6596,6611,109.933037,0.250012
20,NaN,im085,im085,6641,6656,110.683047,0.250000
21,NaN,im085,im085,7229,7244,120.483134,0.249982
22,NaN,im085,im085,7274,7289,121.233112,0.249996
23,NaN,im085,im085,7861,7876,131.016441,0.250001
24,NaN,im069,im069,7906,7921,131.766420,0.250021
25,NaN,im069,im069,8584,8599,143.066397,0.249999
26,NaN,im061,im061,8629,8644,143.816394,0.249975
27,NaN,im061,im061,9214,9229,153.566253,0.249998
28,NaN,im062,im062,9259,9274,154.316261,0.250013
29,NaN,im062,im062,10073,10088,167.883007,0.250000
30,NaN,im066,im066,10118,10133,168.633007,0.250022
31,NaN,im066,im066,10749,10764,179.149647,0.250013
32,NaN,im085,im085,10794,10809,179.899658,0.249984
33,NaN,im085,im085,11336,11351,188.932976,0.250011
34,NaN,im066,im066,11381,11396,189.682988,0.249998
35,NaN,im066,im066,11966,11981,199.432812,0.250020
36,NaN,im063,im063,12011,12026,200.182834,0.249998
37,NaN,im063,im063,12554,12569,209.232814,0.250012
38,NaN,im077,im077,12599,12614,209.982822,0.250003
39,NaN,im077,im077,13186,13201,219.766263,0.249996
40,NaN,im061,im061,13231,13246,220.516232,0.249998
41,NaN,im061,im061,13817,13832,230.282862,0.249994
42,NaN,im066,im066,13862,13877,231.032859,0.250001
43,NaN,im066,im066,14628,14643,243.799517,0.249979
44,NaN,im065,im065,14673,14688,244.549497,0.250020
45,NaN,im065,im065,15215,15230,253.582692,0.249992
46,NaN,im085,im085,15260,15275,254.332690,0.250012
47,NaN,im085,im085,15845,15860,264.082807,0.250024
48,NaN,im062,im062,15890,15905,264.832807,0.250022
49,NaN,im062,im062,16434,16449,273.899491,0.249978
50,NaN,im065,im065,16479,16494,274.649467,0.250009
51,NaN,im065,im065,17110,17125,285.166109,0.250036
52,NaN,im061,im061,17155,17170,285.916085,0.250015
53,NaN,im061,im061,17742,17757,295.699423,0.249983
54,NaN,im061,im061,17787,17802,296.449430,0.249845
55,NaN,im061,im061,18330,18345,305.499282,0.250001
56,NaN,im069,im069,18375,18390,306.249280,0.250001
57,NaN,im069,im069,19188,19203,319.799384,0.250000
58,NaN,im069,im069,19233,19248,320.549382,0.250002
59,NaN,im069,im069,19775,19790,329.582696,0.250001
60,NaN,im077,im077,19820,19835,330.332697,0.249998
61,NaN,im077,im077,20360,20375,339.332669,0.249986
62,NaN,im062,im062,20405,20420,340.082630,0.250000
63,NaN,im062,im062,20945,20960,349.082531,0.249994
64,NaN,im062,im062,20990,21005,349.832500,0.250000
65,NaN,im062,im062,21577,21592,359.615864,0.250002
66,NaN,im085,im085,21622,21637,360.365854,0.250011
67,NaN,im085,im085,22210,22225,370.165929,0.249981
68,NaN,im063,im063,22255,22270,370.915914,0.249989
69,NaN,im063,im063,22842,22857,380.699214,0.250014
70,NaN,im066,im066,22887,22902,381.449215,0.249999
71,NaN,im066,im066,23428,23443,390.465900,0.250007
72,NaN,im069,im069,23473,23488,391.215894,0.249987
73,NaN,im069,im069,24104,24119,401.732416,0.249980
74,NaN,im085,im085,24149,24164,402.482387,0.250030
75,NaN,im085,im085,24691,24706,411.515803,0.250000
76,NaN,im061,im061,24736,24751,412.265801,0.249999
77,NaN,im061,im061,25462,25477,424.365835,0.249999
78,NaN,im063,im063,25507,25522,425.115831,0.250000
79,NaN,im063,im063,26363,26378,439.382471,0.249974
80,NaN,im085,im085,26408,26423,440.132468,0.249999
81,NaN,im085,im085,26996,27011,449.932316,0.249999
82,NaN,im077,im077,27041,27056,450.682286,0.250020
83,NaN,im077,im077,27582,27597,459.698989,0.249977
84,NaN,im066,im066,27627,27642,460.448978,0.249999
85,NaN,im066,im066,28214,28229,470.232405,0.249974
86,NaN,im066,im066,28259,28274,470.982404,0.250002
87,NaN,im066,im066,28799,28814,479.982364,0.250006
88,NaN,im077,im077,28844,28859,480.732381,0.249986
89,NaN,im077,im077,29608,29623,493.465690,0.249999
90,NaN,im077,im077,29653,29669,494.215689,0.266667
91,NaN,im077,im077,30240,30255,503.998870,0.250001
92,NaN,im069,im069,30285,30300,504.748868,0.249999
93,NaN,im069,im069,30872,30887,514.532289,0.250002
94,NaN,im062,im062,30917,30932,515.282311,0.249959
95,NaN,im062,im062,31638,31653,527.298929,0.250001
96,NaN,im063,im063,31683,31698,528.048930,0.249996
97,NaN,im063,im063,32224,32239,537.065602,0.249978
98,NaN,im069,im069,32269,32284,537.815598,0.249975
99,NaN,im069,im069,32812,32827,546.865447,0.250002
100,NaN,im066,im066,32857,32872,547.615425,0.249996
101,NaN,im066,im066,33534,33549,558.898702,0.250036
102,NaN,im061,im061,33579,33594,559.648739,0.250100
103,NaN,im061,im061,34254,34269,570.898862,0.250001
104,NaN,im085,im085,34299,34314,571.648861,0.249998
105,NaN,im085,im085,34930,34945,582.165481,0.250024
106,NaN,im065,im065,34975,34991,582.915479,0.266649
107,NaN,im065,im065,35608,35623,593.465486,0.249981
108,NaN,im065,im065,35653,35668,594.215461,0.249996
109,NaN,im065,im065,36193,36208,603.215306,0.250010
110,NaN,im066,im066,36238,36253,603.965328,0.249998